---
title: "Project Data Cleaning"
output:
  html_document:
    df_print: paged
---
```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = TRUE,   
                      message = FALSE,
                      warning = FALSE,
                      collapse = TRUE,
                      fig.height = 6,
                      fig.width = 6,
                      fig.align = "center",
                      cache = FALSE)
tutorial_html_dependency()
library(tidyverse)
library(plotly)
library(readxl)
library(visdat)
library(foreign)
library(maptools)
library(ggmap)
library(plyr)
library(lubridate)
library(rpart)
library(rpart.plot)
```

```{r eval = FALSE}
lganames <- read.dbf("data/VIC_LGA_POLYGON_shp.dbf")
lgapoly <- readShapePoly("data/VIC_LGA_POLYGON_shp.shp")

library(RColorBrewer)
colors <- brewer.pal(9, "BuGn")

lgapoly.points <- fortify(lgapoly)
lgamap <- get_map(location = c(lon = 144.7852, lat = -37.4713), zoom=6)
ggmap(lgamap) +
  geom_polygon(aes(x = long,
      y = lat,
      group = group),
    data = lgapoly.points,
    color = colors[9],
    fill = colors[6],
    alpha = 0.5) +
labs(x = "Longitude",
  y = "Latitude")
#oz <- get_map(location=c(lon=133.8807,lat=-23.6980),zoom=4)
```


```{r}
all <- read_xlsx("data/Quarterly median rents by local government area - March quarter 2018.xlsx",sheet = 7)
head(all)
all <- all[,-1]
#all <- all %>% rename("Suburb" = "X__2")
colnames(all)[1] <- "Suburb"

vec1 <- seq(2,ncol(all),2)
vec2 <- seq(3,ncol(all),2)

colnames(all)[vec2] <- colnames(all)[vec1]
colnames(all)[vec1] <- paste(colnames(all)[vec2],"_Count",sep='')
colnames(all)[vec2] <- paste(colnames(all)[vec2],"_Median",sep='')
all <- all[-c(1,90),]

all_f <- all %>% gather(variable, values, -Suburb) %>% arrange(Suburb)
all_f <- all_f %>% separate(variable, c("month","year","type"),by="_")
all_medianp <- all_f %>% filter(type == "Median")
all_counts <- all_f %>% filter(type == "Count")

vis_dat(all)
```

```{r "Hongrui's section"}
# to retrieve the average lat and lon from the files
LGACouncil <- read_csv("data/fileslocalgovt.csv")
LatLon <- read_csv("data/Australian_Post_Codes_Lat_Lon 2.csv")
LatLon <- LatLon[,c(1,2,3,6,7)]


LatLon <- LatLon %>% filter(state == 'VIC')
LatLon <- LatLon %>% mutate(Postcode = postcode)
LatLon <- LatLon[,c(6,2,4,5)]
LGACouncil <- LGACouncil[,c(1,4,7)]

#match the coordinate with the LGA
LGAjoin <- left_join(LGACouncil,LatLon, by='Postcode')
LGA_mod <- LGAjoin %>% group_by(Name) %>% mutate(avg_lat = mean(lat),avg_lon = mean(lon))
LGA <- LGAjoin[!duplicated(LGA_mod$LGA),]
LGA <- LGA[,-c(1,4)]
LGA <- LGA[,c(2,1,3,4)]
LGA <- LGA %>% separate(LGA,sep="[(]",c("LGA","Index"))

# remove trailing whitespace
trim.trailing <- function (x) sub("\\s+$", "", x)
LGA$LGA <- trim.trailing(LGA$LGA)
LGA <- LGA[,-2]

```

```{r eval = FALSE "Hongrui's section"}
#plot the LGA in the map of victoria alongsied with its median price in 2018 Mar
all_medianp_2018 <- all_medianp %>% filter(year == 2018)
all_medianp_2018 <- all_medianp_2018 %>% mutate(LGA = Suburb)
all_medianp_2018 <- all_medianp_2018[,c(6,2,3,4,5)]

LGA <- LGA %>% arrange(LGA)
all_medianp_2018 <- all_medianp_2018 %>% arrange(LGA)
loc_2018 <- right_join(LGA,all_medianp_2018,by='LGA')

vic <- get_map(location=c(lon=144.9460, lat=-37.8150), zoom=8)
m <- ggmap(vic) + 
  geom_point(data=loc_2018, aes(x=lon, y=lat,label = values), 
              alpha=1, colour='red', size=0.5)
ggplotly(m)
```



```{r}
agegroup_2017 <- read_xls("data/2017.xls",sheet = "Table 3") 
agegroup_2017<-agegroup_2017[-c(1:8),-c(1)]
agegroup_2017<-agegroup_2017[,-c(2:6)]
agegroup_2017<-agegroup_2017[,-c(3:4)] 
agegroup_2017<-agegroup_2017 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21)) %>%
  filter(state=="Victoria")
```

```{r}
agegroup_2016 <- read_xls("data/2006_2016.xls",sheet = "Table 6") 
agegroup_2016<-agegroup_2016[-c(1:8),-c(1)]
agegroup_2016<-agegroup_2016[,-c(2:6)]
agegroup_2016<-agegroup_2016[,-c(3:4)]
agegroup_2016<-agegroup_2016 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2006 <- read_xls("data/2006_2016.xls",sheet = "Table 3") 
agegroup_2006<-agegroup_2006[-c(1:8),-c(1)]
agegroup_2006<-agegroup_2006[,-c(2:6)]
agegroup_2006<-agegroup_2006[,-c(3:4)]
agegroup_2006<-agegroup_2006 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2015 <- read_xls("data/2010_2015.xls",sheet = "Table 6") 
agegroup_2015<-agegroup_2015[-c(1:7),-c(1)]
agegroup_2015<-agegroup_2015[,-c(2:6)]
agegroup_2015<-agegroup_2015[,-c(3:4)]
agegroup_2015<-agegroup_2015 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2010 <- read_xls("data/2010_2015.xls",sheet = "Table 3") 
agegroup_2010<-agegroup_2010[-c(1:7),-c(1)]
agegroup_2010<-agegroup_2010[,-c(2:6)]
agegroup_2010<-agegroup_2010[,-c(3:4)]
agegroup_2010<-agegroup_2010 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2014 <- read_xls("data/2009_2014.xls",sheet = "Table 6") 
agegroup_2014<-agegroup_2014[-c(1:8),-c(1)]
agegroup_2014<-agegroup_2014[,-c(2:6)]
agegroup_2014<-agegroup_2014[,-c(3:4)]
agegroup_2014<-agegroup_2014 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2009 <- read_xls("data/2009_2014.xls",sheet = "Table 3") 
agegroup_2009<-agegroup_2009[-c(1:8),-c(1)]
agegroup_2009<-agegroup_2009[,-c(2:6)]
agegroup_2009<-agegroup_2009[,-c(3:4)]
agegroup_2009<-agegroup_2009 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2013<- read_xls("data/2008_2013.xls",sheet = "Table 6") 
agegroup_2013<-agegroup_2013[-c(1:8),-c(1)]
agegroup_2013<-agegroup_2013[,-c(2:6)]
agegroup_2013<-agegroup_2013[,-c(3:4)]
agegroup_2013<-agegroup_2013 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2008 <- read_xls("data/2008_2013.xls",sheet = "Table 3") 
agegroup_2008<-agegroup_2008[-c(1:8),-c(1)]
agegroup_2008<-agegroup_2008[,-c(2:6)]
agegroup_2008<-agegroup_2008[,-c(3:4)]
agegroup_2008<-agegroup_2008 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2012 <- read_xls("data/2011_2012.xls",sheet = "Table 6") 
agegroup_2012<-agegroup_2012[-c(1:8),-c(1)]
agegroup_2012<-agegroup_2012[,-c(2:6)]
agegroup_2012<-agegroup_2012[,-c(3:4)]
agegroup_2012<-agegroup_2012 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2011 <- read_xls("data/2011_2012.xls",sheet = "Table 3") 
agegroup_2011<-agegroup_2011[-c(1:8),-c(1)]
agegroup_2011<-agegroup_2011[,-c(2:6)]
agegroup_2011<-agegroup_2011[,-c(3:4)]
agegroup_2011<-agegroup_2011 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2014 <- read_xls("data/2009_2014.xls",sheet = "Table 6") 
agegroup_2014<-agegroup_2014[-c(1:8),-c(1)]
agegroup_2014<-agegroup_2014[,-c(2:6)]
agegroup_2014<-agegroup_2014[,-c(3:4)]
agegroup_2014<-agegroup_2014 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```

```{r}
agegroup_2007 <- read_xls("data/2007.xls",sheet = "Table 3") 
agegroup_2007<-agegroup_2007[-c(1:8),-c(1)]
agegroup_2007<-agegroup_2007[,-c(2:6)]
agegroup_2007<-agegroup_2007[,-c(3:4)]
agegroup_2007<-agegroup_2007 %>%
  select('state'=c(1),'LGA'=c(2),'0-4'=c(3),'5-9'=c(4),'10-14'=c(5),'15-19'=c(6),'20-24'=c(7),'25-29'=c(8),'30-34'=c(9),'35-39'=c(10),'40-44'=c(11),'45-49'=c(12),'50-54'=c(13),'55-59'=c(14),'60-64'=c(15),'65-69'=c(16),'70-74'=c(17),'75-79'=c(18),'80-84'=c(19),'85 and over'=c(20),'total persons'=c(21))
```


```{r}
abslgadata1 <- read_csv("data/ABS_REGIONAL_LGA2017-enp1.csv")
abslgadata2 <- read_csv("data/ABS_REGIONAL_LGA2017-enp2.csv")
abslgaviclgas <- read_xlsx("data/abslgaviclgas.xlsx")
abslgadata <- rbind(abslgadata1,abslgadata2) 
#we want to remove anything related to age, gender or race as this is another part of the analysis
abslgadata <- abslgadata[!grepl("ERP",abslgadata$MEASURE),] #population data
abslgadata <- abslgadata[!grepl("CENSUS",abslgadata$MEASURE),] #census data
abslgadata <- abslgadata[!grepl("BD",abslgadata$MEASURE),] #birth/death data
#remove unnecessary columns
abslgadata <- abslgadata %>% select(-REGIONTYPE,-`Geography Level`,-LGA_2017,-FREQUENCY,-Frequency,-TIME,-`Flag Codes`,-Flags)
#identify victorian lgas
abslgaviclgas <- abslgaviclgas %>% mutate (VIC_LGAS=sub("(.*)\\s.*","\\1",VIC_LGAS)) %>% mutate (VIC_LGAS=sub("(.*)\\s.*","\\1",VIC_LGAS)) %>% mutate (VIC_LGAS=sub("(.*)\\s.*","\\1",VIC_LGAS))
#filter out all the data points which are not related to victoria
absviclgadata <- filter(abslgadata,Region %in% abslgaviclgas$VIC_LGAS)
as.tibble(unique(absviclgadata$`Data item`)) #Shows unique data items within abslgadata
#this tells us that there are 398 unique data items
as.tibble(unique(absviclgadata$Region)) #Shows unique LGAs within abslgadata
#this tells us that there are 552 unique LGAs
#abslgadata <- abslgadata %>% 
glimpse(absviclgadata)
```


```{r,kevan's section}
#tidy data into usable form, keeping suburb, values and date
medianrentps <- all_medianp %>%  
  mutate(date=paste("01-",month,"-",year)) %>% 
  mutate(date=dmy(date)) %>% 
  select("Suburb","values","date") %>%
  mutate(values=as.numeric(values))
medianrentps_plot <- medianrentps %>% ggplot(aes(x=date,y=values,colour=Suburb))+geom_line()
ggplotly(medianrentps_plot)
```

```{r, kevan's section 2}
#medianrentps <- medianrentps %>% filter(Suburb=="Bayside")
#identify regression trees. this will help to identify regions of similar trend
medianrentps_rp <- rpart(values~date,data=medianrentps,control=rpart.control(minsplit=3))
medianrentps_pred <- medianrentps %>% mutate(pred=predict(medianrentps_rp,medianrentps))
medianrentps_rp_plot <- ggplot(medianrentps_pred) + geom_point(aes(x=date,y=values)) + geom_line(aes(x=date,y=pred),colour="orange",size=1.5)
ggplotly(medianrentps_rp_plot)
#applying a regression tree allows us to identify different partitions in the data. there final partition and most relevant (as it is closest to present time) begins in 01-Jun-2011. This is convenient, as the ABS has begun collecting specific regional data on LGAs beginning
```

```{r, kevan's section 3}
#the types of data given by the ABS regional data is numerous.
#as_tibble(unique(absviclgadata$`Data item`))
#this shows that there are a total of 398 different data items! majority of this data is collected annually, however some of these data items have missing data items
absviclgadata_spreadbyyear <- absviclgadata %>% spread(key=Time,value=Value)
vis_dat(absviclgadata_spreadbyyear,warn_large_data=FALSE)
#we notice that there is a significant amount of missing data, notably in 2017. We wish to use data points with at least 6 points of data, i.e. 2011-2016. 2017 is a bonus!
```
```{r, "Kevan's section 3"}
#we then remove the data that has less than 6 data points and see what information we're left with. we do not wish to impute the missing values as it may be making the incorrect assumption that the change of all these data items are related to each other per LGA. 
absviclgadata_countyears <- absviclgadata %>% group_by(`Data item`,Region) %>% dplyr::summarise(no_years = sum(!is.na(Time))) 
nodataitems_g7 <- absviclgadata_countyears %>% filter(no_years>=7) %>% nrow()
nodataitems_g6 <- absviclgadata_countyears %>% filter(no_years>=6) %>% nrow()
nodataitems <- absviclgadata_countyears %>% nrow()
as.tibble(list(Name=c("No. of data items with more than 7 years of data","No. of data items with more than 6 years of data","Total number of data items"),Count=c(nodataitems_g7,nodataitems_g6,nodataitems),Percentage=c(nodataitems_g7/nodataitems,nodataitems_g6/nodataitems,nodataitems/nodataitems)))
#this tells us that there is only 2569 of 22268 data items that have 6 more more points of data. that's only about 11.54% of all data points! Even worse, only 2.4% of the data items actually have all 7 years of data! it would be possible to impute the missing values for data items with 2 or more values, however it would not be extremely accurate. Let's try and do some analysis without imputing.

#first, lets find out what kind of information we have left, and how many lgas in each one.
absviclgadata_unique_g6 <- absviclgadata_countyears %>% filter(no_years == 6) %>% group_by(`Data item`) %>% dplyr::summarise(lga_count = n())
absviclgadata_unique_g6
#this has left us with only 40 actual different data points, when we started with 295!! 
absviclgadata_unique_g6 %>% filter(lga_count > 20)
#of these 40, it must be noted that only 18 of these data items have over 300 points of data. Of these, majority of them are actually vehicle statistics. maybe this analysis should be on whether the number of vehicles in the area have a significant effect on rental price
```

```{r}
#lets do that! it must be noted that although 6 points of data for each LGA does not provide very reliable information, however expanding this to over 500 different LGAs can provide a reasonable conclusion if there is a significant pattern between all of them.
mvcdata <- absviclgadata %>% dplyr::filter(grepl("MVC",MEASURE)) %>% select(-MEASURE)
#lets look at a sample of the data for one LGA, and plot it against its median rental price
mvcdata <- mvcdata %>% mutate(Time=dmy(paste("31-12-",Time)))

l <- ggplot(mvcdata,aes(x=Time,y=Value,colour=Region))+geom_line()+facet_wrap(~`Data item`)
ggplotly(l)
```

```{r "Hongrui's section"}
#look at historical rental price reacted to the Australian economy
gdp <- read_csv("data/GDP.csv")
gdp <- gdp %>% filter(LOCATION == "AUS")
gdp <- gdp[,c(1,6,7)]
#historical gdp plot
gdp_plot <- gdp %>% ggplot(aes(x=TIME,y=Value))+geom_line()
ggplotly(gdp_plot)

# compute the gdp growth rate
gdp_slope <- gdp %>% mutate(volume = Value - lag(Value, default = Value[1]))
gdp_slope <- gdp_slope %>% mutate(rate = volume / lag(Value, default = Value[1]))
rate_plot <- gdp_slope %>% ggplot(aes(x=TIME,y=rate))+geom_line()
ggplotly(rate_plot)

#as we can see, when there is a decrease on economics growth, there will be a boost on rental price, referring to Kevon's medianrentps_plot, as it's shown in year 2007 - 2008, and 2011 - 2012
```
```{r "Hongrui's section"}
# compute the distance from LGA to Melbourne city, and see if there is anything to do with rental price.
distance <- read_csv("data/LGA_Profile_2014_beta.csv")
distance <- distance[,c(2,9)]
distance <- distance %>% separate(LGA,sep="[(]",c("LGA","Index"))
trim.trailing <- function (x) sub("\\s+$", "", x)
distance$LGA <- trim.trailing(distance$LGA)
distance <- distance[,-2]

all_medianp$Suburb[all_medianp$Suburb == 'Mornington Penin\'a'] <- 'Mornington Peninsula'
all_medianp <- all_medianp %>% filter(Suburb != 'Metro',Suburb != 'Non-Metro', Suburb != 'Group Total', Suburb != 'Victoria')
all_medianp$values <- as.integer(all_medianp$values)
all_medianp$values[is.na(all_medianp$values)] <- mean(all_medianp$values, na.rm = T)
all_medianp_avg <- aggregate(all_medianp[,5],list(all_medianp$Suburb),mean)
colnames(all_medianp_avg)[1] <- 'LGA'
dis_price_join <- left_join(all_medianp_avg,distance,by='LGA')

dis <- ggplot(dis_price_join,aes(x=Distance_to_Melbourne_in_km,y=values)) + geom_point()
ggplotly(dis)
```
```{r "Hongrui's seciton""}

all_counts_mod <- all_counts %>%
  filter(Suburb != 'Metro',Suburb != 'Non-Metro', Suburb != 'Group Total', Suburb != 'Victoria',Suburb != 'Melbourne')
medianrentcts <- all_counts_mod%>%  
  mutate(date=paste("01-",month,"-",year)) %>% 
  mutate(date=dmy(date)) %>% 
  select("Suburb","values","date") %>%
  mutate(values=as.numeric(values))
medianrentcts_plot <- medianrentcts %>% ggplot(aes(x=date,y=values,colour=Suburb))+geom_line()
ggplotly(medianrentcts_plot)
```



